//------------------------------------------------------------------------------
// <auto-generated>
//     Strongly-typed accessor for Localization\Strings.resx (the single English source of UI texts).
//     Same shape as the output of the ResXFileCodeGenerator (StronglyTypedResourceBuilder);
//     Visual Studio regenerates this file when Strings.resx is edited in the resource editor.
//     When editing Strings.resx by hand, add a matching property below (or use L10n.T("Key")).
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrowserSelect.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrowserSelect.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language_Label {
            get {
                return ResourceManager.GetString("Language_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new language will be used the next time BrowserSelect starts..
        /// </summary>
        internal static string Language_RestartRequired {
            get {
                return ResourceManager.GetString("Language_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language_RestartTitle {
            get {
                return ResourceManager.GetString("Language_RestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface language. Every language added to BrowserSelect is listed here..
        /// </summary>
        internal static string Language_Tooltip {
            get {
                return ResourceManager.GetString("Language_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes, are you sure you want to close without saving ?.
        /// </summary>
        internal static string Settings_UnsavedChanges {
            get {
                return ResourceManager.GetString("Settings_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        internal static string Settings_UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("Settings_UnsavedChangesTitle", resourceCulture);
            }
        }
    }
}
